server:
  port: 3009
spring:
  data:
    mongodb:
      database: lor-latest-videos

lor:
  you-tube:
    scheduler:
      enabled: false
  json-data:
    channels-url: https://lor-gamewise-data.s3.amazonaws.com/channels.json
    champions-url: https://lor-gamewise-data.s3.amazonaws.com/champions.json
